quarkus:
  hibernate-orm:
    database:
      generation: drop-and-create

mp:
  messaging:
    incoming:
      wordsin-panache:
        connector: smallrye-kafka
        topic: wordsin-panache
      wordsin-hibernate:
        connector: smallrye-kafka
        topic: wordsin-hibernate